### DISCUSSION TITLE
Text Replacement feature not working when show_forwarded_from is true

### DISCUSSION THREAD

**Discussion by lehuuhai014** [aahnik/tgcf#143] [Q&A] [answered]
Hi @aahnik, Have a nice day! 
I want to ask, Are this plugin work?

I fill this simple text into the config file, the Filter works smoothly however, the replace plugins not work with me. am I wrong at any point?

```yaml
forwards:
  - source: -1001442302246
    dest: [-1001433758953]
show_forwarded_from: true
plugins:
  replace:
    text:
      god: devil
      smart: idiot
      original: new
```

**Comment by ankit-sinha-18** [comment, marked as answer]
When any message is forwarded with quotes in Telegram then it is not possible to edit that message as it contains the original message with tag created from someone that can't be changed.

This is the Telegram issue, and I think there is no edit for forwarded message because anyone can manipulate the message and spread in public that he has written something wrong And that's why Telegram has not provided edit function for forwarded messages.

To benefit from text replacement, use `show_forwarded_from: false` (false is default, so you don't even need to write that line)

**Reply by lehuuhai014** [reply]
Hi @ankit-sinha-18, thank you for your repone.
I filled in the config file. However, when I send "god" in the source channel, it will send "god" into the dest. ^^
In my terminal: 

```shell
PS C:\Users\Huu Hai\Documents\my-project> tgcf live
tgcf filter data loaded
Loaded plugin filter 
Loaded plugin replace
FileType.NOFILE
```
```yaml
plugins:
   filter:
     text:
       blacklist: ["nope"]
   replace:
     text:
       god: devil
       tokyo: delhi
```
