### DISCUSSION TITLE
Queries related to GitHub Action

### DISCUSSION THREAD

**Discussion by ankit-sinha-18** [aahnik/tgcf#145] [Q&A] [answered]
**Q1. For how long workflow can run continuously??**

**Q2. How to do cron jobs in GitHub action?**
_I have tried this code For running every 10 minutes but code didn't run itself_
```
on:
   schedule:
    - cron:  '*/10 * * * *'
```
**Q3. Is timezone for cron job is UTC?? Can it be changed according to different timezone?**

**Comment by aahnik** [comment, marked as answer]
- **ans 1.** for 72 hours
- **ans 2**. the [tgcf-on-gh-action repo](https://github.com/aahnik/tgcf-on-gh-action) has been updated with an example 
-  **ans 3** the time zone of cron is UTC, and cannot be changed. This is Github's feature, we can't do anything about it. You may use an online time converter to convert the time from IST to UTC

**Reply by ankit-sinha-18** [reply]
<details>
<summary> 👉  This is the syntax of my yml file </summary>



```
name: tgcf-past

on:
  schedule:
    - cron:  '*/10 * * * *'



jobs:
  tgcf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: aahnik/tgcf@main
        env:
          TGCF_MODE: "past"
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: push files changed

```
</details>
