### DISCUSSION TITLE
Text replacement not working in Windows when string contains certain characters [now fixed]

### DISCUSSION THREAD

**Discussion by hrylx** [aahnik/tgcf#205] [Q&A] [answered]
Hi,
i tried to replace complete strings, but it doesn´t seem to work - is this possible at all, or am i doing something wront?
code example:
```
(...)
plugins:
  filter:
    text:
      blacklist: ["nope"]
  replace:
    text:
      "ohne Gewähr!": dog
```

Edit:
It works in general and with other strings -  the Problem in this case is the encoding, which doesn´t seem to recognize the "ä" as a valid character. Anything that can be done about that? 
Maybe i can encode it somehow, so that the bot understands it?
