### DISCUSSION TITLE
Delete Sync Feature Not Working

### DISCUSSION THREAD

**Discussion by Abhishek0863** [aahnik/tgcf#272] [Q&A] [answered]
Delete Sync Feature is not working for me , can anyone check if my configuration is correct or not.

```
forwards:
  - source: -1001164044873
    dest: [-1001252877360]

plugins:
  filter:
    text:
      blacklist: ["nope"]

  replace:
    text:
      god: devil
      tokyo: delhi

  delete_sync: true
```
