### DISCUSSION TITLE
How to remove characters in messenger with filter

### DISCUSSION THREAD

**Discussion by copcon121** [aahnik/tgcf#276] [Q&A] [answered]
I want to use filter for remove characters as "-". Example : A-B-C = ABC . Anybody can help me?

**Comment by vitor-gsousa** [comment, marked as answer]
Didn't test it but from what i understood:
```
plugins:
  replace:
    text:
      "-": ""

    regex: true
```
