### DISCUSSION TITLE
How to write multiple keywords for filter plugin

### DISCUSSION THREAD

**Discussion by Abhishek0863** [aahnik/tgcf#311] [Q&A]
I am unable to write more than 1 keyword to use for filter. Please help. @aahnik @tissole

**Comment by tissole** [comment]
Give more details, what filter do you want to use? Provide an example so I can test it.

**Reply by Abhishek0863** [reply]
i want to add multiple blacklist keywords 

```
plugins:
  filter:
    text:
      blacklist: ["nope"]
  replace:
    text:
      god: devil
      tokyo: delhi
```

here nope is one blacklisted word i want more words, how to write them.
