### DISCUSSION TITLE
Using whitelist and replace in config

### DISCUSSION THREAD

**Discussion by miodragk76** [aahnik/tgcf#362] [Q&A]
Hello,

Great software and I am eternally grateful.

I can't manage to set regex replace and whitelist in one config file.
They work separately, but not together. I probably didn't guess the right structure.

Can I have a little help :)

```
plugins:
  replace:
    text:
      "\nTRIGGER_WORD": "ADDED_TEXT\nTRIGGER_WORD"
      regex: true
```

**Comment by miodragk76** [comment]
....and how to add more than one regex replace?

**Comment by miodragk76** [comment]
I figured it out :)

```
plugins:
  replace:
    text:
      "\nTRIGGER_WORD": "ADDED_TEXT\nTRIGGER_WORD"
      regex: true
  filter:
    text:
      whitelist: ["ONLY_MESSAGES_CONTAINING_TXT"]

```
