### DISCUSSION TITLE
How to have docker persistent storage for tgcf

### DISCUSSION THREAD

**Discussion by vtmocanu** [aahnik/tgcf#393] [Q&A] [answered]
Hello,
I haven't started using tgcf yet, so I might miss something obivous, but looking at the code/wiki/issues/etc, I wonder were are the settings stored? Are they lost when the container is replaced? Or can we mount a local folder to keep them persistent?
Thank you for sharing this awsome tool!
Vlad

Later edit:
you probably have to mount tgcf.config.json so it is persistent.

**Comment by cosinguyen** [comment, marked as answer]
Hi,
Check out my docker-compose to be able to manage config files
```
version: '3.4'
 
services:         
  tele1:
    container_name: tele1_container
    image: aahnik/tgcf:latest
    environment:
      - PASSWORD=anypasswordyouwant
    restart: always
    volumes:
      - "/usr/tgcf/:/app"
```

https://github.com/aahnik/tgcf/discussions/395#discussioncomment-4376242
