### DISCUSSION TITLE
How to deploy tgcf using Nginx ?

### DISCUSSION THREAD

**Discussion by aahnik** [aahnik/tgcf#395] [Q&A] [answered]
Description of configuration and steps required to deploy tgcf using Nginx.

**Comment by cosinguyen** [comment, marked as answer]
Hello everyone,
I just went through this yesterday, you can refer to these articles hope it can help you:
https://discuss.streamlit.io/t/how-to-use-streamlit-with-nginx/378
https://discuss.streamlit.io/t/errors-while-trying-to-deploy-a-streamlit-app-with-nginx/30266

But I use tgcf's docker and Nginx Proxy Manager so my handling is a bit different. My `docker-compose.yml` below
```
version: '3.4'
 
services:         
  tele1:
    container_name: tele1_container
    image: aahnik/tgcf:latest
    environment:
      - PASSWORD=anypasswordyouwant
    restart: always
    volumes:
      - "/usr/tgcf/:/app"

  nginx:
    container_name: nginx_container
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    restart: always
    volumes:
      - "/usr/src/nginx/data:/data"
      - "/usr/src/nginx/letsencrypt:/etc/letsencrypt"
```
We don't need to configure the open port for tgcf because everything will be taken care of by docker.
Run the command `docker-compose up -d`, after finishing launching the docker, now access to <IPAddress>: 81
Follow the instructions to create a Nginx account, nagative to Hosts -> Proxy Hosts -> Add Proxy Host

![image](https://user-images.githubusercontent.com/51023369/206988185-2f3a68f2-c9cc-4308-b443-85e134a4a63e.png)
Fill in the domain or sub-domain information, the internal address please enter the name of the docker app and the default port 8501 of tgcf
Note that you choose: **Websocket support**
Right now you can access by domain name or subdomain just now you can access tgcf, this way you can create multiple tgcf docker to use and manage access with Nginx, just add docker-compose and different docker app name, different domain or sub-domain and point correctly on Nginx.
```
version: '3.4'
 
services:         
  tele1:
    container_name: tele1_container
    image: aahnik/tgcf:latest
    environment:
      - PASSWORD=anypasswordyouwant
    restart: always
    volumes:
      - "/usr/tgcf1/:/app"

  tele2:
    container_name: tele2_container
    image: aahnik/tgcf:latest
    environment:
      - PASSWORD=anypasswordyouwant
    restart: always
    volumes:
      - "/usr/tgcf2/:/app"

  tele2:
    container_name: tele3_container
    image: aahnik/tgcf:latest
    environment:
      - PASSWORD=anypasswordyouwant
    restart: always
    volumes:
      - "/usr/tgcf3/:/app"
      
  tele3:
    container_name: tele4_container
    image: aahnik/tgcf:latest
    environment:
      - PASSWORD=anypasswordyouwant
    restart: always
    volumes:
      - "/usr/tgcf4/:/app"

  nginx:
    container_name: nginx_container
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    restart: always
    volumes:
      - "/usr/src/nginx/data:/data"
      - "/usr/src/nginx/letsencrypt:/etc/letsencrypt"
```

If you want to use SSL, you can switch to the SSL tab and register a new free SSL from Let's Encrypt, you can do it while creating the Host or later.

![image](https://user-images.githubusercontent.com/51023369/206990408-da58b105-99d8-42e6-bca0-b7acfd0e849e.png)

Note that you are required to open ports 80 and 443 for successful SSL registration and port 81 can be open at least when you access Nginx Proxy Manager.
Hope this post is helpful !!!!
