### DISCUSSION TITLE
How to make tgcf work for multi source and multi destinition?

### DISCUSSION THREAD

**Discussion by ehs4nm** [aahnik/tgcf#68] [Q&A] [answered]
If someone needs to monitor and forward from multiple channels to a peer multi-channels, how should i approach? make the chat ids an array?

**Comment by aahnik** [comment, marked as answer]
The bot can work from multi-source to multi-destination.

Read this [How to configure tgcf ?](https://github.com/aahnik/tgcf/wiki/How-to-configure-tgcf-%3F)

example:

```yaml
forwards:
  - source: -1001412118156
    dest: [-1001461332656, -1001457230530]
  - source: -1003456789
    dest: [-13456789067]

```

**Reply by ehs4nm** [reply]
Thanks man. Keep up with this great work.

**Reply by aahnik** [reply]
you can star this project to support. This will help others discover it.

Also you may make a post in social media about tgcf and give link to it.

**Reply by bhbmalka** [reply]
can multi-source to multi-destination have different blacklist or whitelist?

**Reply by Chappie18** [reply]
> The bot can work from multi-source to multi-destination.
> 
> Read this [How to configure tgcf ?](https://github.com/aahnik/tgcf/wiki/How-to-configure-tgcf-%3F)
> 
> example:
> 
> ```yaml
> forwards:
>   - source: -1001412118156
>     dest: [-1001461332656, -1001457230530]
>   - source: -1003456789
>     dest: [-13456789067]
> ```

Is it possible to configure multi source to one destination?

**Reply by tissole** [reply]
@bhbmalka Currently no, but separate plugins per source is coming #176
@Chappie18 Yes, you can configure multi-source to one destination, like that

```
forwards:
  - source: -100xxxxxxxxxx
    dest: [-100zzzzzzzzzz]
  - source: -100yyyyyyyyyy
    dest: [-100zzzzzzzzzz]
```
