### ISSUE TITLE
Filtering by file type

### ISSUE THREAD

**Issue by aahnik** [aahnik/tgcf#120]
allow only certain types of files, or ban certain types of files.

this is requested by multiple people #116 , #61 , #6

**Comment by aahnik** [comment]
This feature can be used by using the `filter` plugin and specifying the files you want to filter

```yaml
plugins:
  filter:
    files:
      whitelist: [document]
```

you can use a blacklist instead of a whitelist also

```yaml
     blacklist: [video]
```


The valid file types are :

```shell

    audio
    gif
    video
    video_note
    sticker
    contact
    photo
    document
```
