### ISSUE TITLE
yaml.reader.ReaderError: unacceptable character, special characters are not allowed

### ISSUE THREAD

**Issue by cat157** [aahnik/tgcf#207]
After `tgcf live` i got:
```  File "/usr/local/lib/python3.8/dist-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "tgcf.config.yml", position 225
```
tgcf.config.yml:
```
plugins:
  filter:
    text:
      blacklist: ["тест"]
```
problem in the word "тест", in previous versions everything is ok
