### ISSUE TITLE
Join all channels to creat a Timeline

### ISSUE THREAD

**Issue by Trustdee** [aahnik/tgcf#216]
Possible to add feature of joining all channels together to create a timeline , this will make it easy to follow all my channels in one channel , image below .

![image](https://user-images.githubusercontent.com/17923943/122340975-88e89800-cf75-11eb-8ae5-34857e86e5b0.png)

**Comment by aahnik** [comment]
You can forward messages from multiple channels to a single channel.

Just write in your configuration.

For example you want to forward from "channel1" , "channel2", "channel3" to "myChannel"

```yaml
forwards:
    - source: channel1
      dest: [myChannel]
    - source: channel2
      dest: [myChannel]
    - source: channel3
      dest: [myChannel]
```
