### ISSUE TITLE
help pls on TGCF_CONFIG

### ISSUE THREAD

**Issue by AmirulAndalib** [aahnik/tgcf#242]
```
admins: []
# when tgcf is run in live mode, the admins can run commands to change the configuration

forwards:
  - source: https://t.me/joinchat/XXXXXXXXXXX
    dest: https://t.me/joinchat/XXXXXXXXX
    # use username or link of the entity


show_forwarded_from: true

plugins:
  filter:
    text:
      blacklist:
  replace:
    text:

```

is this config ok?  i get some error pls help .....Deploying to Heroku
