### ISSUE TITLE
Error message - Help with Termux / Android [ unpack requires a buffer of 275 bytes ]

### ISSUE THREAD

**Issue by vicenterusso** [aahnik/tgcf#243]
**Describe the bug**
Tried to run on android and got the following error message: **`unpack requires a buffer of 275 bytes`**

**To Reproduce**
1) Installed `termux` on android
2) Installed `tgcf`
3) Retrieved credentials (`APP_ID`, `API_HASH` and `SESSION_STRING`) -- using as **user**
4) Saved credentials on `.env`
5) Created a file name `tgcf.config.yml` on the same folder as `.env`
6) Executed `tgcg live` in the same config/env folder

**Expected behavior**
I expected to run without any errors

**Screenshots**
https://i.imgur.com/mQ6SIPv.png

**Additional context**
Scenario: Trying to forward messages from a private channel (without @username) to another private channel (that I own)

I'm not sure if it's the right way to set the source channel (with the displayed name).

More info:
- I don't have the source @username,
- I don't have a fixed link to join the channel. I can login through a bot that authorizes me to join

My `tgcf.config.yml`

```yaml
admins: [my-own-username-without-@] 

forwards:
  - source: "Name Of The Private Source Channel"
    dest: [https://t.me/link-ti-my-own-private-channel]

show_forwarded_from: true
```
