### ISSUE TITLE
ChatIdInvalidError

### ISSUE THREAD

**Issue by IR4N0nY** [aahnik/tgcf#277]
**Describe the bug**
```
ChatIdInvalidError: Invalid object ID for a chat. Make sure to pass the right types, for instance making sure that the request is
                             designed for chats (not channels/megagroups) or otherwise look for a different one more suited\nAn example working with a megagroup and
                             AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest instead (caused by SendMessageRequest)
```

**Expected behavior**
hello i just want to forward messages from a channel to another channel but when the message received from source channel this error happened
my config.yml:
```
admins: [rrrrrrr] 
# when tgcf is run in live mode, the admins can run commands to change the configuration

forwards:
  - source: 87424621
    dest: [-1524514483]
    # use username or link of the entity


show_forwarded_from: false  
```
