### ISSUE TITLE
Case insensitive text filtering

### ISSUE THREAD

**Issue by RebbePod** [aahnik/tgcf#93]
I just want to start off saying: thank you very much @aahnik everything is working perfectly!

Just a nice to have feature would be to have the whitelist and blacklist filters, have an optional match-case / match whole word option.
(The current default is to match case and not match whole words)

**Comment by aahnik** [comment]
that's a good idea. I will try to implement it soon!

**Comment by ehs4nm** [comment]
i want to add something here: words start with characters like '@' or '#' can't be filtered.

**Comment by aahnik** [comment]
> i want to add something here: words start with characters like '@' or '#' can't be filtered.

is this a feature request ?  or you mean this happens ?

by the way, this feature is coming in the next release!

**Comment by aahnik** [comment]
hi @ehs4nm and @RebbePod 

After v0.1.29, by default text filtering will be case insensitive.

If you need case-sensitive text filtering, you can set it to true.

see example [configuration](https://github.com/aahnik/tgcf/wiki/How-to-configure-tgcf-%3F)

```yaml
plugins:
  filter:
    text:
      case_sensitive: true # default is false if you don't write this line
      whitelist: ["this word"]
      blacklist: ["hello"]
```
